version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = ""
s3_bucket = ""
s3_prefix = ""
region = ""
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
image_repositories = []
